name: Android CI Build From Source

on:
  push:
    branches: [ "min" ]
  pull_request:
    branches: [ "min" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository source code.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # Step 2: Set up the Java Development Kit (JDK).
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # Step 3: Set up the Android NDK (for our C++ engine).
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true

      # Step 4: Add the NDK's glslc compiler to the system PATH.
      - name: Add NDK glslc to PATH
        run: echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      # Step 5: Install a specific version of Gradle.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      # Step 6: Create the necessary Gradle configuration files on the fly.
      # This is the critical step that follows your instructions.
      - name: Create Gradle Build Files
        working-directory: ./SLearn
        run: |
          # Create settings.gradle
          echo "pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }" > settings.gradle
          echo "dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }" >> settings.gradle
          echo "rootProject.name = 'SLearn'" >> settings.gradle
          echo "include ':app'" >> settings.gradle

          # Create top-level build.gradle
          echo "plugins { id 'com.android.application' version '8.2.0' apply false }" > build.gradle

      # Step 7: Generate the Gradle Wrapper scripts (gradlew).
      # This command reads the new settings.gradle and creates the gradlew files.
      - name: Generate Gradle Wrapper
        working-directory: ./SLearn
        run: gradle wrapper

      # Step 8: Grant execute permission to the now-existing Gradle wrapper.
      - name: Make gradlew executable
        working-directory: ./SLearn
        run: chmod +x ./gradlew

      # Step 9: Build the application using the generated wrapper.
      - name: Build with Gradle Wrapper
        working-directory: ./SLearn
        run: ./gradlew :app:assembleDebug

      # Step 10: Upload the final build artifact.
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: SLearn/app/build/outputs/apk/debug/app-debug.apk